AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  FastAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FastAPI-UserAPI
      Handler: main.lambda_handler
      Runtime: python3.12
      CodeUri: .
      MemorySize: 512
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/Users"
      Environment:
        Variables:
          TABLE_NAME: Users
          REGION: ap-south-1
      Events:
        RootPath:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /
            Method: get
        UserPath:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /users/{name}
            Method: get
        ProxyPath:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /{proxy+}
            Method: any

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  UserApiUrl:
    Description: "Users API endpoint URL"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/users/{name}"
